/*
 * GPIO_Driver_Cfg.h
 *
 *  Created on: Jan 23, 2018
 *      Author: zsolt.balo
 */

/*
 typedef struct
{
	GPIO_TypeDef* GPIO_Port;
	uint16 GPIO_Pins[16];
	uint16 GPIO_Pin_Mode[16];
	uint16 GPIO_Pin_Cfg[16];
	uint32 GPIO_Cfg_Instances;
}GPIO_Driver_Setup_Type;
 */
#ifndef GPIO_DRIVER_CFG_H_
#define GPIO_DRIVER_CFG_H_

#include "GPIO_Driver.h"

#define GPIO_DRIVER_GPIOA 				  	OK
#define GPIO_DRIVER_GPIOB 				  	OK
#define GPIO_DRIVER_GPIOC 				  	NOK
#define GPIO_DRIVER_GPIOD 				  	OK
#define GPIO_DRIVER_GPIOE 				  	NOK
#define GPIO_DRIVER_GPIOF 				  	NOK
#define GPIO_DRIVER_GPIOG 				  	NOK
#define GPIO_DRIVER_GPIOH 				  	NOK
#define GPIO_DRIVER_GPIOI 				  	NOK
#define GPIO_DRIVER_GPIOJ 				  	NOK
#define GPIO_DRIVER_GPIOK 				  	NOK
#define GPIO_DRIVER_INSTANCE_NUM 			((uint32)0x03)

GPIO_Driver_Setup_Type GPIO_SETUP[GPIO_DRIVER_INSTANCE_NUM]=
{
	{
		GPIOB,
		{0x01},
		1,
		{GPIO_DRIVER_OUTPUT_MODE},
		{GPIO_DRIVER_OUTPUT_PP},
		{GPIO_DRIVER_VERY_HIGH_SPEED_100MHZ},
		{GPIO_DRIVER_PUPD_NOPULL}
	},
	{
		GPIOA,
		{
		0x06,0x07,0x05,
		0x02,0x04,0x01
		},
		6,
		{
		 GPIO_DRIVER_ALTERNATE_FUNCTION_MODE,GPIO_DRIVER_ALTERNATE_FUNCTION_MODE,GPIO_DRIVER_ALTERNATE_FUNCTION_MODE,
		 GPIO_DRIVER_OUTPUT_MODE,GPIO_DRIVER_OUTPUT_MODE,GPIO_DRIVER_ALTERNATE_FUNCTION_MODE
		},
		{
		 DEFAULT,GPIO_DRIVER_OUTPUT_PP,GPIO_DRIVER_OUTPUT_PP,
		 GPIO_DRIVER_OUTPUT_PP, GPIO_DRIVER_OUTPUT_PP,GPIO_DRIVER_OUTPUT_PP
		},
		{
		 DEFAULT,GPIO_DRIVER_HIGH_SPEED_50MHZ,GPIO_DRIVER_HIGH_SPEED_50MHZ,
		 GPIO_DRIVER_HIGH_SPEED_50MHZ, GPIO_DRIVER_HIGH_SPEED_50MHZ,GPIO_DRIVER_HIGH_SPEED_50MHZ
		},
		{
		 GPIO_DRIVER_PUPD_NOPULL,GPIO_DRIVER_PUPD_NOPULL,GPIO_DRIVER_PUPD_NOPULL,
		 GPIO_DRIVER_PUPD_NOPULL, GPIO_DRIVER_PUPD_NOPULL,GPIO_DRIVER_PUPD_NOPULL
		}
	},
	{
		GPIOD,
		{0x0C,0x0D},
		2,
		{GPIO_DRIVER_ALTERNATE_FUNCTION_MODE,GPIO_DRIVER_ALTERNATE_FUNCTION_MODE},
		{DEFAULT,DEFAULT},
		{GPIO_DRIVER_HIGH_SPEED_50MHZ,GPIO_DRIVER_HIGH_SPEED_50MHZ},
		{GPIO_DRIVER_PUPD_NOPULL,GPIO_DRIVER_PUPD_NOPULL}
	}
};

#endif /* GPIO_DRIVER_CFG_STM32F103_H_ */
