/*
 * USART_Driver_Cfg.h
 *
 *  Created on: Jan 31, 2018
 *      Author: zsolt.balo
 */

#ifndef USART_DRIVER_CFG_H_
#define USART_DRIVER_CFG_H_

#include "USART_Driver.h"

#define USART_DRIVER_USART1_SELECT					OK
#define USART_DRIVER_USART2_SELECT					NOK
#define USART_DRIVER_USART3_SELECT					NOK
#define USART_DRIVER_USART4_SELECT					NOK
#define USART_DRIVER_USART5_SELECT					NOK
#define USART_DRIVER_USART6_SELECT					NOK

#ifndef USART_DRIVER_BAUDRATE
	#error "You have to define the Baud rate with #define BAUDRATE <selected BaudRateValue>"
#endif

#if((USART_DRIVER_USART1_SELECT)||(USART_DRIVER_USART6_SELECT))
	#define USART_DRIVER_WORKING_FREQUENCY_2 		84000000
#endif

#if(((USART_DRIVER_USART2_SELECT)||(USART_DRIVER_USART3_SELECT)||(USART_DRIVER_USART4_SELECT)||(USART_DRIVER_USART5_SELECT)))
	#define USART_DRIVER_WORKING_FREQUENCY_1 		42000000
#endif


#ifndef USART_DRIVER_WORKING_FREQUENCY_2
	#ifndef USART_DRIVER_WORKING_FREQUENCY_1
		#error "You have to define the working frequency of the APB2 or APB1"
	#endif
#endif

#define USART_DRIVER_OVERSAMPLING					USART_DRIVER_OVERSAMPLING_BY_16
#define USART_DRIVER_WORD_LENGTH					USART_DRIVER_8_DATA_BITS
#define USART_DRIVER_PARITY_CONTROL_ENABLE			NOK

#if (USART_DRIVER_PARITY_CONTROL_ENABLE == OK)
#define USART_DRIVER_PARITY_SELECTION				USART_DRIVER_EVEN_PARITY
#endif

#define USART_DRIVER_TRANSMITTER_ENABLE				OK
#define USART_DRIVER_RECEIVER_ENABLE				OK
#define USART_DRIVER_STOP_BIT_SELECT				USART_DRIVER_1_STOP_BIT
#define USART_DRIVER_HALF_DUPLEX_SELECTION			NOK

#endif /* USART_DRIVER_CFG_H_ */
